// NOTE: cc elf-sections.c -o elf-sections
#include <locale.h>
#include <stdio.h>
#include <wchar.h>
// NOTE: սա ձեր Elf64_Ehdr-ը արդեն ունի
#include <elf.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

int  main(int argc, char *argv[])
{
	if (argc < 2) {
		return 1;
	}

	if (setlocale(LC_ALL, "") == NULL) {
		return 1;
	}

	wprintf(L"[*] նախընտրած ֆայլը` %s\n", argv[1]);

	const int file = open(argv[1], O_RDONLY);
	if (file == -1) {
		wprintf(L"[!] չհաջողվեց բացել ֆայլը, կոդը՝ %i\n", errno);
		return 1;
	}

	struct stat info;
	if (fstat(file, &info) == -1) {
		wprintf(L"[!] չհաջողվեց ստանալ ֆայլի չափը, կոդը՝ %i\n", errno);
		close(file);
		return 1;
	}

	// NOTE: ֆայլը ամողջովին հիշողության մեջ եմ դնում որ ամեն անգամ read չկանչեմ․․․
	const char *map = mmap(NULL, info.st_size, PROT_READ, MAP_SHARED, file, 0);
	if (map == MAP_FAILED) {
		close(file);
		wprintf(L"[!] չհաջողվեց ֆայլը տանել RAM, կոդը՝ %i\n", errno);
		return 1;
	}

	const Elf64_Ehdr *ehdr = (Elf64_Ehdr *)map;
	{
		wprintf(L"[*] Ֆայլի վերլուծությունը`\n");
		// NOTE: վերջ․․․ արդեն անհետաքրքիր ա, զուտ պետք ա տպեք բոլոր դաշտերը
		wprintf(L"\tmagic:      %02x %02x %02x %02x\n", ehdr->e_ident[EI_MAG0], ehdr->e_ident[EI_MAG1],
			ehdr->e_ident[EI_MAG2], ehdr->e_ident[EI_MAG3]);
		wprintf(L"\tclass:      %s\n", (ehdr->e_ident[EI_CLASS] == ELFCLASS64) ? "64-bit" : "32-bit");
		wprintf(L"\tendianness: %s\n",
			(ehdr->e_ident[EI_DATA] == ELFDATA2LSB) ? "Little Endian" : "Big Endian");
		wprintf(L"\tversion:    %d\n", ehdr->e_ident[EI_VERSION]);
		// BUG: պետքա տպել բոլոր դաշտերը․․․
	}

	// NOTE: նայի, զուտ `e_shoff` դաշտի մեջի արժեքով առաջ եմ գնում,
	// ինքը ցույց ա տալիս ինչքան ֆայլի մեջ թռնեմ որ գամ section table-ի վրա
	const Elf64_Shdr *shdrs = (Elf64_Shdr *)(map + ehdr->e_shoff);
	// NOTE: `shstr` յուրահատուկ section-ն ա, ցույց ա տալիս որտեղ են ELF ֆայլի տողերը (string֊երը),
	// նշանակում ա որ թռնեք իրա հասցեի վրա, կկարողանանք section-ի անունները ստանանք․
	// `sh_name`-ը offset-ա `shstr`-ի մեջ, ոչ թե հենց `char*`
	const Elf64_Shdr *shdr_str = &shdrs[ehdr->e_shstrndx];
	// NOTE: վերևում մենք `shstr` section-ի header֊ը ստացանք, հիմա գնանք իրա պարունակության տեղը գտնենք
	// էս պահից սկսած ունենք բոլոր string-երը ELF-ին պատկանող
	const char *shstr_buf = (char *)(map + shdr_str->sh_offset);
	// NOTE: ELF-ը իրա սկզբի header-ում (ehdr-ն որից մի հատ կա, հենց offset 0-ում ա), ասում ա քանի հատ section
	// ունենք․․․ զուտ գնանք բոլորի վրայով
	// օգտագործեք `readelf -S <file>` ստուգելու համար
	wprintf(L"\t==================== SECTIONS ====================\n");
	for (Elf64_Half i = 0; i < ehdr->e_shnum; i++) {
		const Elf64_Shdr *shdr = &shdrs[i];
		const char *name = shstr_buf + shdrs[i].sh_name;
		wprintf(L"\t| %-20s | 0x%-8lx | %-10lu |\n", name, shdr->sh_offset, shdr->sh_size);
		// BUG: մնացած դաշտերնել արժի տպել․․․ բայց ես էլ հավես չունեմ․․․
		// դրանք պարզ printf-եր պետքա լինեն, սա էր «բարդ» մասը
	}

	close(file);
	return 0;
}




// NOTE: cc elf-header.c -o elf-header
#include <locale.h>
#include <stdio.h>
#include <wchar.h>
// NOTE: սա ձեր Elf64_Ehdr-ը արդեն ունի
#include <elf.h>
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

int
main(int argc, char *argv[])
{
	if (argc < 2) {
		return 1;
	}

	if (setlocale(LC_ALL, "") == NULL) {
		return 1;
	}

	wprintf(L"[*] նախընտրած ֆայլը` %s\n", argv[1]);

	const int file = open(argv[1], O_RDONLY);
	if (file == -1) {
		wprintf(L"[!] չհաջողվեց բացել ֆայլը, կոդը՝ %i\n", errno);
		return 1;
	}

	struct stat info;
	if (fstat(file, &info) == -1) {
		wprintf(L"[!] չհաջողվեց ստանալ ֆայլի չափը, կոդը՝ %i\n", errno);
		close(file);
		return 1;
	}

	// NOTE: ֆայլը ամողջովին հիշողության մեջ եմ դնում որ ամեն անգամ read չկանչեմ․․․
	const char *map = mmap(NULL, info.st_size, PROT_READ, MAP_SHARED, file, 0);
	if (map == MAP_FAILED) {
		close(file);
		wprintf(L"[!] չհաջողվեց ֆայլը տանել RAM, կոդը՝ %i\n", errno);
		return 1;
	}

	Elf64_Ehdr *header;
	header = (Elf64_Ehdr *)map;

	wprintf(L"[*] Ֆայլի վերլուծությունը`\n");
	// NOTE: վերջ․․․ արդեն անհետաքրքիր ա, զուտ պետք ա տպեք բոլոր դաշտերը, ստուգելու համար գրի `readelf -h <file>`
	wprintf(L"\tmagic:      %02x %02x %02x %02x\n", header->e_ident[EI_MAG0], header->e_ident[EI_MAG1],
		header->e_ident[EI_MAG2], header->e_ident[EI_MAG3]);
	wprintf(L"\tclass:      %s\n", (header->e_ident[EI_CLASS] == ELFCLASS64) ? "64-bit" : "32-bit");
	wprintf(L"\tendianness: %s\n", (header->e_ident[EI_DATA] == ELFDATA2LSB) ? "Little Endian" : "Big Endian");
	wprintf(L"\tversion:    %d\n", header->e_ident[EI_VERSION]);
	// BUG: պետքա տպել բոլոր դաշտերը․․․

	close(file);
	return 0;
}